// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StructurMessegerFullUserActyvyti.DAL.DB;

#nullable disable

namespace StructurMessegerFullUserActyvyti.Migrations;

[DbContext(typeof(ConnectingDatabase))]
partial class ConnectingDatabaseModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("StructurMessegerFullUserActyvyti.DAL.DB.UserDataTable", b =>
            {
                b.Property<Guid>("UserID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserID");

                b.ToTable("UserDataTable");
            });

        modelBuilder.Entity("StructurMessegerFullUserActyvyti.DAL.DB.UserFriendsTable", b =>
            {
                b.Property<string>("Email")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Email");

                b.ToTable("UserFriendsTable");
            });
#pragma warning restore 612, 618
    }
}
